//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BonusDayOffs = new HashSet<BonusDayOff>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public short DaysUsed { get; set; }
        public int Account_ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BonusDayOff> BonusDayOffs { get; set; }
    }
}
